version: '2'
services:
    level-app:
        image: level
        external_links:
            - level-mysql:mysql
            - level-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/level?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    level-mysql:
        extends:
            file: mysql.yml
            service: level-mysql
    level-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: level-elasticsearch
